### ISSUE TITLE
RuntimeError when running SMPLX

### ISSUE THREAD

**Issue by Wentworth1028** [mks0601/ExAvatar_RELEASE#38]
Hi, thanks for sharing this amazing work. 

When making custom video with Camera option 2 (`python run.py --root_path $ROOT/data/Custom/data/$SUBJECT_ID`), I encoutered the following error in the middle of fitting SMPLX:

```sh
['epoch 0/3 itr_data 0/2 itr_opt 98/500:', 'lr: 0.1', 'loss_smplx_kpt_proj: 0.0504', 'loss_smplx_kpt_proj_wo_fo: 0.0504', 'loss_flame_kpt_proj: 0.0289', 'loss_flame_to_smplx_v2v: 0.0090']
When forward(), smplx_inputs['root_pose'].device: cuda:6, flame_inputs['root_pose'].device: cuda:6
When forward(), smplx_inputs['root_pose'].device: cuda:4, flame_inputs['root_pose'].device: cuda:4
When forward(), smplx_inputs['root_pose'].device: cuda:2, flame_inputs['root_pose'].device: cuda:2
When forward(), smplx_inputs['root_pose'].device: cuda:1, flame_inputs['root_pose'].device: cuda:1
When forward(), smplx_inputs['root_pose'].device: cuda:5, flame_inputs['root_pose'].device: cuda:5
When forward(), smplx_inputs['root_pose'].device: cuda:3, flame_inputs['root_pose'].device: cuda:3
When forward(), smplx_inputs['root_pose'].device: cuda:7, flame_inputs['root_pose'].device: cuda:7
When forward(), smplx_inputs['root_pose'].device: cuda:0, flame_inputs['root_pose'].device: cuda:0
/home/cv_stu_13/Project/ExAvatar/fitting/main/../output/result/1
['epoch 0/3 itr_data 0/2 itr_opt 99/500:', 'lr: 0.1', 'loss_smplx_kpt_proj: 0.0504', 'loss_smplx_kpt_proj_wo_fo: 0.0504', 'loss_flame_kpt_proj: 0.0290', 'loss_flame_to_smplx_v2v: 0.0091']
When forward(), smplx_inputs['root_pose'].device: cuda:5, flame_inputs['root_pose'].device: cuda:5
When forward(), smplx_inputs['root_pose'].device: cuda:3, flame_inputs['root_pose'].device: cuda:3
When forward(), smplx_inputs['root_pose'].device: cuda:2, flame_inputs['root_pose'].device: cuda:2
When forward(), smplx_inputs['root_pose'].device: cuda:1, flame_inputs['root_pose'].device: cuda:1
When forward(), smplx_inputs['root_pose'].device: cuda:7, flame_inputs['root_pose'].device: cuda:7
When forward(), smplx_inputs['root_pose'].device: cuda:6, flame_inputs['root_pose'].device: cuda:6
When forward(), smplx_inputs['root_pose'].device: cuda:4, flame_inputs['root_pose'].device: cuda:4
When forward(), smplx_inputs['root_pose'].device: cuda:0, flame_inputs['root_pose'].device: cuda:0
Traceback (most recent call last):
  File "/home/cv_stu_13/Project/ExAvatar/fitting/main/fit.py", line 213, in <module>
    main()
  File "/home/cv_stu_13/Project/ExAvatar/fitting/main/fit.py", line 118, in main
    loss, out = trainer.model(smplx_inputs, flame_inputs, data, return_output=((epoch==cfg.end_epoch-1) and (itr_opt==cfg.itr_opt_num-1)))
  File "/home/cv_stu_13/miniconda3/envs/mmpose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cv_stu_13/miniconda3/envs/mmpose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cv_stu_13/miniconda3/envs/mmpose/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/home/cv_stu_13/miniconda3/envs/mmpose/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/cv_stu_13/miniconda3/envs/mmpose/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "/home/cv_stu_13/miniconda3/envs/mmpose/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/cv_stu_13/miniconda3/envs/mmpose/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/home/cv_stu_13/miniconda3/envs/mmpose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cv_stu_13/miniconda3/envs/mmpose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cv_stu_13/Project/ExAvatar/fitting/main/model.py", line 246, in forward
    loss['smplx_to_flame_lap'] = self.lap_reg(smplx_mesh_wo_pose_wo_expr[:,smpl_x.face_vertex_idx,:], flame_mesh_wo_pose_wo_expr.detach()) * is_not_neck * 100000
  File "/home/cv_stu_13/miniconda3/envs/mmpose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cv_stu_13/miniconda3/envs/mmpose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cv_stu_13/Project/ExAvatar/fitting/main/../common/nets/loss.py", line 120, in forward
    lap_out = self.compute_laplacian(out, self.neighbor_idxs, self.neighbor_weights)
  File "/home/cv_stu_13/Project/ExAvatar/fitting/main/../common/nets/loss.py", line 111, in compute_laplacian
    lap = x + (x[:, neighbor_idxs] * neighbor_weights[None, :, :, None]).sum(2)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)
```
Seems like input tensors were not in the same device before calling `compute_laplacian`.

Do you have any insights on what might be causing this? I’d be grateful for any guidance you can provide.

**Comment by mks0601** [comment]
Hi, could you run it after setting `export CUDA_VISIBLE_DEVICES=0`?

**Comment by Wentworth1028** [comment]
Thanks for the reply, I will try it and give you back.

**Comment by Wentworth1028** [comment]
Problem solved. Really appreciate your support.
